apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-executor-rolebinding
  namespace: sykang
subjects:
- kind: ServiceAccount
  name: default
  namespace: sykang
roleRef:
  kind: Role
  name: pod-executor-role
  apiGroup: rbac.authorization.k8s.io